In [13]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [14]:
from sklearn.datasets import make_regression


In [15]:
X,y=make_regression(n_samples=100,n_features=2,n_targets=1,n_informative=2,noise=10,random_state=42)

In [16]:
df=pd.DataFrame({'feature1':X[:,0],'feature2':X[:,1],'target':y})

In [17]:
df

,feature1,feature2,target
0,-1.191303,0.656554,-49.265023
1,0.058209,-1.142970,-85.162387
2,0.586857,2.190456,211.225658
3,0.473238,-0.072829,29.196562
4,0.738467,0.171368,84.348096
...,...,...,...
95,0.361396,1.538037,147.505343
96,0.296120,0.261055,32.710111
97,-0.990536,-0.566298,-141.334380
98,-0.460639,1.057122,48.782598


In [18]:
import plotly.express as px
import plotly.graph_objects as go

In [19]:
fig=px.scatter_3d(df,x='feature1',y='feature2',z='target')
fig.show()

In [20]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [21]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [22]:
lr=LinearRegression()   

In [23]:
lr.fit(X_train,y_train) 

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [24]:
y_pred=lr.predict(X_test)

In [25]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
print("MAE",mean_absolute_error(y_test,y_pred))
print("MSE",mean_squared_error(y_test,y_pred))
print("R2 score",r2_score(y_test,y_pred))

MAE 9.667801070655653
MSE 154.6277268949053
R2 score 0.9836279308340317


In [26]:
import numpy as np

# 1. Create the base ranges
x = np.linspace(-5, 5, 10)
y = np.linspace(-5, 5, 10)

# 2. Build the coordinate grids
xGrid, yGrid = np.meshgrid(x, y) # Standard order is (x, y)

# 3. Flatten and stack them into a 2D coordinate matrix (Define 'final' FIRST)
# Using np.c_ is a clean shortcut for stacking columns
final = np.c_[xGrid.ravel(), yGrid.ravel()]

# 4. Generate predictions and reshape into the 10x10 surface matrix
z_final = lr.predict(final).reshape(10, 10)
z = z_final


In [27]:
fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')

fig.add_trace(go.Surface(x = x, y = y, z =z ))

fig.show()                          

In [28]:
lr.coef_

array([86.31018533, 73.66927906])

In [29]:
lr.intercept_   

np.float64(0.06595480364319961)

In [30]:
from sklearn.datasets import load_diabetes

In [31]:
X,y=load_diabetes(return_X_y=True)

In [32]:
print(X.shape)
print(y.shape)

(442, 10)
(442,)


In [33]:
from sklearn.model_selection import train_test_split

In [34]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [35]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [36]:
lr.fit(X_train,y_train)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [37]:
y_pred=lr.predict(X_test)

In [38]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.4526027629719195

In [39]:
# 10 features so 10 coefficients
lr.coef_

array([  37.90402135, -241.96436231,  542.42875852,  347.70384391,
       -931.48884588,  518.06227698,  163.41998299,  275.31790158,
        736.1988589 ,   48.67065743])

In [40]:
lr.intercept_

np.float64(151.34560453985995)

In [51]:
import numpy as np

beta0 = np.ones((X_train.shape[0], 1))  # Column of ones

print(beta0.shape)
print(X_train.shape)

X_train_new = np.concatenate((beta0, X_train), axis=1)

print(X_train_new.shape)
X_train_new

(353, 1)
(353, 10)
(353, 11)


array([[ 1.00000000e+00,  7.07687525e-02,  5.06801187e-02, ...,
         3.43088589e-02,  2.73640491e-02, -1.07769750e-03],
       [ 1.00000000e+00, -9.14709343e-03,  5.06801187e-02, ...,
         7.12099798e-02,  2.72478149e-04,  1.96328371e-02],
       [ 1.00000000e+00,  5.38306037e-03, -4.46416365e-02, ...,
        -2.59226200e-03,  1.70360713e-02, -1.35040182e-02],
       ...,
       [ 1.00000000e+00,  3.08108295e-02, -4.46416365e-02, ...,
        -3.94933829e-02, -1.09032507e-02, -1.07769750e-03],
       [ 1.00000000e+00, -1.27796319e-02, -4.46416365e-02, ...,
        -2.59226200e-03, -3.84597173e-02, -3.83566597e-02],
       [ 1.00000000e+00, -9.26954778e-02, -4.46416365e-02, ...,
        -3.94933829e-02, -5.14218980e-03, -1.07769750e-03]],
      shape=(353, 11))

### Multiple Linear Regression from scratch

In [56]:
class MultipleLinearRegressionScratch:
    def __init__(self):
        self.coef_ = None
        self.intercept_ = None
        self.betas = None

    def fit(self,X_train,y_train):
        beta0 = np.ones((X_train.shape[0], 1))  # Column of ones
        X_train_new = np.concatenate((beta0, X_train), axis=1)
        
        self.betas=np.linalg.inv(X_train_new.T.dot(X_train_new)).dot(X_train_new.T).dot(y_train)
        self.coef_= self.betas[1:]
        self.intercept_= self.betas[0]
    
    def predict(self,X_test):
        beta0 = np.ones((X_test.shape[0], 1))  # Column of ones
        X_test_new = np.concatenate((beta0, X_test), axis=1)
        return X_test_new.dot(self.betas)

In [57]:
lr=MultipleLinearRegressionScratch()
lr.fit(X_train,y_train)
y_pred=lr.predict(X_test)
r2_score(y_test,y_pred)

0.4526027629719186

In [58]:
lr.coef_

array([  37.90402135, -241.96436231,  542.42875852,  347.70384391,
       -931.48884588,  518.06227698,  163.41998299,  275.31790158,
        736.1988589 ,   48.67065743])

In [59]:
lr.intercept_

np.float64(151.34560453985995)

In [60]:
lr.betas

array([ 151.34560454,   37.90402135, -241.96436231,  542.42875852,
        347.70384391, -931.48884588,  518.06227698,  163.41998299,
        275.31790158,  736.1988589 ,   48.67065743])